export const initialState = {
  your_title: "",
  your_first_name: "",
  your_last_name: "",
  your_date_of_birth: "",
  your_nationality: "",
  your_gender: "",
  your_email: "",
  your_mobile: "",
  your_landline: "",
  address_1: "",
  address_2: "",
  address_3: "",
  city: "",
  postcode: "",
  salary_type: "salary",
  salary_amount: "",
  specific_role: "",
  job_title_location: "",
  have_transport: false,
  have_disability: "",
  national_insurance_number: "",
  share_code: "",
};
